name: CI 

on: [push]

jobs:
    
  srv1:
    runs-on: [ubuntu-latest]
    steps:
      - name: Pull repo and start docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            docker-compose up -d
